version: "3"
services:
  redis-abc:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - redis

  backend:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - redis-abc
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 8081:8081
    networks:
      - redis

networks:
  redis:
    driver: bridge
