version: "3"
services:
  backend:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: "./backend"
    # depends_on:
    #   - redis
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3000:3000
    networks:
      - redis

  redis-abc:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  redis:
    driver: bridge
